name: Dutch Michael
markdown: kramdown

timezone: America/New_York

title: Dutch Michael's homepage
description: Bookmark this to keep an eye on my project updates!

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

permalink: /blog/:year/:month/:day/:title