name: Dutch Michael
# markdown: kramdown

timezone: America/New_York

title: Tactile theme
description: Tactile is a theme for GitHub Pages.

theme: jekyll-theme-tactile
# remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

show_downloads: true
google_analytics: [Your Google Analytics tracking ID]

permalink: /blog/:year/:month/:day/:title